---
plugin: aws_ec2
aws_profile: itmentor
region: ap-southeast-1
filters:
  tag:Name: 
    - '*-ec2'
  instance-state-name : running
hostnames:
- ip-address
keyed_groups:
  - key: tags.Name
    prefix: tag
    separator: "_"